/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Flia Alcalá Castro
 */
public class DialogProperty extends javax.swing.JDialog {

    /**
     * Creates new form DialogProperty
     */
    MonopolyForm parent;
    ImageIcon img;

    public DialogProperty(MonopolyForm parent, boolean modal, ImageIcon img) {
        super(parent, modal);
        initComponents();
        this.parent = parent;
        propertyImg.setIcon(new ImageIcon(img.getImage().getScaledInstance(propertyImg.getWidth(), propertyImg.getHeight(), Image.SCALE_DEFAULT)));
        this.setDefaultCloseOperation(0);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        propertyName = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        owner = new javax.swing.JLabel();
        propertyImg = new javax.swing.JLabel();
        auctionBtn = new javax.swing.JButton();
        buyBtn = new javax.swing.JButton();
        payRentBtn = new javax.swing.JButton();
        endTurnBtn = new javax.swing.JButton();
        mortgageBtn = new javax.swing.JButton();
        payMortgageBtn = new javax.swing.JButton();
        buyHouseBtn = new javax.swing.JButton();
        sellHouseBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Property name:");

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Price:");

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Owner:");

        propertyName.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        propertyName.setForeground(new java.awt.Color(255, 255, 255));
        propertyName.setText("San Luis Norte");

        price.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        price.setForeground(new java.awt.Color(255, 255, 255));
        price.setText("$60");

        owner.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        owner.setForeground(new java.awt.Color(255, 255, 255));
        owner.setText("None");

        auctionBtn.setBackground(new java.awt.Color(195, 194, 194));
        auctionBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        auctionBtn.setText("Auction");

        buyBtn.setBackground(new java.awt.Color(195, 194, 194));
        buyBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        buyBtn.setText("Buy");

        payRentBtn.setBackground(new java.awt.Color(195, 194, 194));
        payRentBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        payRentBtn.setText("Pay rent");

        endTurnBtn.setBackground(new java.awt.Color(153, 0, 0));
        endTurnBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        endTurnBtn.setText("End turn");
        endTurnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endTurnBtnActionPerformed(evt);
            }
        });

        mortgageBtn.setBackground(new java.awt.Color(195, 194, 194));
        mortgageBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        mortgageBtn.setText("Mortgage");

        payMortgageBtn.setBackground(new java.awt.Color(195, 194, 194));
        payMortgageBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        payMortgageBtn.setText("Pay mortgage");

        buyHouseBtn.setBackground(new java.awt.Color(195, 194, 194));
        buyHouseBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        buyHouseBtn.setText("Buy house");

        sellHouseBtn.setBackground(new java.awt.Color(195, 194, 194));
        sellHouseBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        sellHouseBtn.setText("Sell house");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(propertyImg, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(propertyName)
                            .addComponent(price)
                            .addComponent(owner)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(buyBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(auctionBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sellHouseBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(payMortgageBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buyHouseBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mortgageBtn)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(payRentBtn)
                .addGap(55, 55, 55)
                .addComponent(endTurnBtn)
                .addGap(93, 93, 93))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {endTurnBtn, payRentBtn});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {mortgageBtn, payMortgageBtn});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buyHouseBtn, sellHouseBtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(propertyName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(price))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(owner))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(propertyImg, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(auctionBtn)
                    .addComponent(mortgageBtn)
                    .addComponent(buyHouseBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buyBtn)
                    .addComponent(payMortgageBtn)
                    .addComponent(sellHouseBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endTurnBtn)
                    .addComponent(payRentBtn))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {endTurnBtn, payRentBtn});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void endTurnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endTurnBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_endTurnBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton auctionBtn;
    private javax.swing.JButton buyBtn;
    private javax.swing.JButton buyHouseBtn;
    private javax.swing.JButton endTurnBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton mortgageBtn;
    private javax.swing.JLabel owner;
    private javax.swing.JButton payMortgageBtn;
    private javax.swing.JButton payRentBtn;
    private javax.swing.JLabel price;
    private javax.swing.JLabel propertyImg;
    private javax.swing.JLabel propertyName;
    private javax.swing.JButton sellHouseBtn;
    // End of variables declaration//GEN-END:variables
}
